# Configuration File

# Database Info
drivername: postgres
host: localhost
database: perception_db
username: perception_user
password: perception_passwd

# Application Info
discovery_mode: passive

# You should not use this
# Setup PKI and stop being lazy!
# Svc Account password
# svc_account_passwd: insecure_password

# Splunk Indexer Info
splunk_indexer: True
splunk_host: ip_addr
splunk_username: username
splunk_password: super_secure_password
splunk_api_port: 8089
splunk_index: perception_index